import { renderReader } from '../renderer/index.js';

export function exportJson(document) { return JSON.stringify(document, null, 2); }

export function exportStandaloneHtml(document) {
  const reader = renderReader(document);
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(document.title)}</title><style>body{margin:0;background:#101923;color:#f7f4ec;font-family:system-ui,-apple-system,sans-serif}.wrap{max-width:780px;margin:auto;padding:48px 22px 72px}.document-reader{border:1px solid #33485e;border-radius:18px;padding:28px;background:#152230}.document-template,.conclusion-label,.section-label,.reader-flow-label{color:#ffbd62;font:10px monospace;letter-spacing:.14em}.reader-status{float:right;border:1px solid #385069;border-radius:999px;padding:5px 9px;color:#8da1b5;font:10px monospace}.document-reader h2{font-size:clamp(34px,7vw,62px);line-height:.95;letter-spacing:-.06em;margin:18px 0 14px}.document-thesis{color:#afbdc9;line-height:1.55}.reader-visual,.relationship-section{margin:26px 0;padding:16px;border:1px solid #33485e;border-radius:14px;background:#1a2a3b}.reader-flow{display:flex;align-items:stretch;gap:8px;margin-top:12px}.reader-node{display:flex;flex:1;min-height:76px;flex-direction:column;justify-content:space-between;padding:12px;border:1px solid #55718c;border-radius:12px;background:#1b2b3b}.reader-node-index,.reader-arrow,.card-number{color:#78bfff;font:10px monospace}.reader-node strong{font-size:14px}.reader-node small{color:#8298aa;font:10px monospace;text-transform:uppercase}.reader-arrow{align-self:center;font-size:20px}.document-relations{display:grid;gap:9px;padding:0;list-style:none}.document-relations li{display:grid;grid-template-columns:1fr auto 1fr;gap:8px;align-items:center;color:#e8e5dc;font-size:12px}.document-relations li span:last-child{text-align:right}.document-relations b{color:#ffbd62;font:10px monospace}.reader-insight{border-top:1px solid #2e4051;border-bottom:1px solid #2e4051;padding:16px 0;margin:22px 0}.reader-insight span{color:#78bfff;font:10px monospace}.reader-insight p{color:#d6e2ed;font-size:13px;line-height:1.5}.explanation-cards{display:grid;gap:8px}.explanation-card{display:grid;grid-template-columns:32px 1fr;gap:10px;border:1px solid #33485e;border-radius:12px;padding:12px;background:#152230}.explanation-card h3{margin:0 0 5px;font-size:14px}.explanation-card p{margin:0;color:#9fb0bf;font-size:12px;line-height:1.45}.reader-sources{color:#72879a;font:10px monospace;margin-top:22px}.reader-sources a{color:#8ec7ff}@media(max-width:560px){.reader-flow{flex-direction:column}.reader-arrow{transform:rotate(90deg);align-self:center}.document-relations li{grid-template-columns:1fr}.document-relations li span:last-child{text-align:left}}</style></head><body><main class="wrap">${reader}</main></body></html>`;
}
function escapeHtml(value = '') { return String(value).replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' })[char]); }
