import { createDocument, parseDocument, serializeDocument, validateDocument } from '../document/index.js';
import { createHistory, dispatch, undo, redo } from '../actions/index.js';
import { exportStandaloneHtml } from '../export/index.js';
import { worldToScreen, screenToWorld } from '../canvas/index.js';
const document = createDocument({ title: 'Smoke test', thesis: 'A', nodes: ['A', 'B', 'C'], template: 'feedback-loop' });
if (!validateDocument(document).valid) throw new Error('document invalid');
let history = createHistory(document);
history = dispatch(history, { type: 'move', ids: ['node-1'], dx: 12, dy: 8 });
history = dispatch(history, { type: 'resize', id: 'node-1', dw: 20, dh: 10 });
history = undo(history); history = redo(history);
if (history.document.elements[0].x !== 12 || history.document.elements[0].width !== 170) throw new Error('history failed');
const roundTrip = parseDocument(serializeDocument(history.document));
if (!exportStandaloneHtml(roundTrip).startsWith('<!doctype html>')) throw new Error('export failed');
const point = worldToScreen({ x: 10, y: 20 }, { x: 2, y: 3, zoom: 2 });
const restored = screenToWorld(point, { x: 2, y: 3, zoom: 2 });
if (restored.x !== 10 || restored.y !== 20) throw new Error('viewport transform failed');
console.log('html-anything smoke test: ok');
